create extension if not exists vector;

create table if not exists document_chunks (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  document_id varchar(64) not null,
  chunk_id varchar(160) not null,
  chunk_index integer not null,
  chunk_text text not null,
  chunk_summary text,
  char_start integer,
  char_end integer,
  metadata_json jsonb,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint uk_document_chunks_user_document_index unique (user_id, document_id, chunk_index),
  constraint uk_document_chunks_user_chunk unique (user_id, chunk_id)
);

create index if not exists idx_document_chunks_user_document
  on document_chunks(user_id, document_id, chunk_index);
